import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>앞으로 한걸음</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bodyContainer}>
        <div className={styles.headContainer}>
          <h1>One Step</h1>
          <form>
            <input />
          </form>
        </div>
        <div className={styles.contentContainer}>
          <div className={styles.content}>
            <p>기록용</p>
          </div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
          <div className={styles.content}></div>
        </div>
      </div>
    </>
  );
}
