import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { useEffect, useRef, useState } from "react";
import ContentList from "@/components/ContentList";
import { IContent } from "@/types/content";
import { getDateFormat } from "@/utils/date";

export default function Home() {
  const [contents, setContents] = useState([] as IContent[]);
  const [inputData, setInputData] = useState("");
  const id = useRef(0);

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setInputData(e.target.value);
  };

  const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const currentTime = getDateFormat();
    const content = {
      id: ++id.current,
      data: inputData,
      createdAt: currentTime,
    };
    setContents([...contents, content]);
    setInputData("");
  };

  const getContentData = async () => {
    return await fetch("http://localhost:4000/posts", {
      method: "GET",
    }).then((res) => res.json());
  };

  const addContentData = async () => {
    await fetch("http://localhost:4000/posts", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        data: inputData,
        createdAt: getDateFormat(),
      }),
    }).then((res) => {
      console.log(res.status);
      return res.status;
    });
  };

  useEffect(() => {
    const updateData = async () => {
      const content = await getContentData();
      setContents(content);
    };
    updateData();
  }, []);
  return (
    <>
      <Head>
        <title>앞으로 한걸음</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.bodyContainer}>
        <div className={styles.headContainer}>
          <h1>One Step</h1>
          <form onSubmit={handleSubmit}>
            <input
              onChange={handleChange}
              name="todo-input"
              placeholder="목표를 입력하세요"
              value={inputData}
            />
            <button onClick={addContentData}>추가</button>
          </form>
        </div>
        <div>
          <button onClick={getContentData}>겟</button>
        </div>
        <div className={styles.contentContainer}>
          <ContentList contents={contents} />
        </div>
      </div>
    </>
  );
}
